<?xml version="1.0"?>

<robot name="mavs" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:property name="scale_factor" value="0.2" />
  <xacro:property name="mesh_mode" value="1"/>
  <!-- Vehicle geometry -->
  <xacro:property name="base_link" value="base_link" />
  <xacro:property name="base_width" value="1.9" />
  <xacro:property name="base_length" value="3.3" />
  <xacro:property name="base_height" value="1.2" />
  <xacro:property name="base_clearance" value="0.5" />

  <xacro:property name="base_geometry">
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}" />
    </geometry>
  </xacro:property>

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.393" />
  <xacro:property name="wheel_width" value="0.1" />
  <xacro:property name="wheel_mass" value="2.5" /> <!-- in kg-->

  <xacro:property name="la" value="1.6" />
  <xacro:property name="lb" value="1.7" />
  <xacro:property name="wheel_base" value="1" />

  <!-- LiDAR properties -->
  <xacro:property name="lidar_z" value="${base_height/2 + 0.1}" />
  <xacro:property name="lidar_x" value="${base_length/2-0.1}" />
  <xacro:property name="topic" value="/lidar_points" />

  <!-- Necessary includes -->
  <xacro:include filename="$(find mavs_description)/urdf/hmmwv.xacro" />
  <xacro:include filename="$(find mavs_description)/urdf/vehicle_gazebo.urdf.xacro" />

  <!-- Bolt-on sensors go here -->
  <xacro:include filename="$(find mavs_description)/urdf/velodyne_16.xacro"/>
  <velodyne_16 parent="${base_link}" lidar_x="${lidar_x}" lidar_z="${lidar_z}"/>
</robot>
