<?xml version="1.0"?>
<robot name="velodyne_16_bot" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- Vehicle geometry -->
  <xacro:property name="base_link" value="base_link" />
  <xacro:property name="width" value="1.9" />
  <xacro:property name="length" value="3.3" />
  <xacro:property name="height" value="1.3" />
  <xacro:property name="base_geometry">
    <geometry>
      <box size="${length} ${width} ${height}" />
    </geometry>
  </xacro:property>

  <!-- Vehicle position -->
  <xacro:property name="x" value="0" />
  <xacro:property name="y" value="0" />
  <xacro:property name="z" value="0" />

  <xacro:property name="roll" value="0" />
  <xacro:property name="pitch" value="0" />
  <xacro:property name="yaw" value="0" />
  <xacro:property name="block_origin">
    <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}" />
  </xacro:property>

  <!-- LiDAR properties -->
  <xacro:property name="lidar_z" value="${height/2 + 0.1}" />
  <xacro:property name="lidar_x" value="${length/2-0.1}" />
  <xacro:property name="topic" value="/lidar_points" />

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find mavs_description)/urdf/materials.xacro" />

  <!-- Vehicle modeled as a giant block -->
  <xacro:include filename="$(find mavs_description)/urdf/block.xacro"/>
  <block base_link="${base_link}">
    <xacro:insert_block name="block_origin" />
    <xacro:insert_block name="base_geometry" />
  </block>

  <!-- Bolt-on sensors go here -->
  <xacro:include filename="$(find mavs_description)/urdf/velodyne_16.xacro"/>
  <velodyne_16 parent="${base_link}" lidar_x="${lidar_x}" lidar_z="${lidar_z}"/>

</robot>
